### ISSUE TITLE
Building ament_cmake_core package is failing on linux

### ISSUE THREAD

**Issue by mbatc** [RoboStack/vinca#41]
I been trying to build all packages locally for ros-humble and ran into an issue building ament_cmake_core. I have only been trying to build for linux64 so I am not sure what the status of this is for other platforms.

The error I'm getting is,

```
-- Found Python3: $PREFIX/bin/python (found version "3.10.12") found components: Interpreter 
-- ament_cmake_core 1.3.5
CMake Error: File /tmp/tmp5br8m21flocal_setup.bash.in does not exist.
CMake Error at cmake/environment_hooks/ament_generate_package_environment.cmake:73 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  cmake/environment_hooks/ament_cmake_environment_hooks_package_hook.cmake:26 (ament_generate_package_environment)
  cmake/core/ament_execute_extensions.cmake:48 (include)
  cmake/core/ament_package.cmake:66 (ament_execute_extensions)
  CMakeLists.txt:21 (ament_package)


CMake Error: File /tmp/tmpyky4jsrzlocal_setup.sh.in does not exist.
CMake Error at cmake/environment_hooks/ament_generate_package_environment.cmake:73 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  cmake/environment_hooks/ament_cmake_environment_hooks_package_hook.cmake:26 (ament_generate_package_environment)
  cmake/core/ament_execute_extensions.cmake:48 (include)
  cmake/core/ament_package.cmake:66 (ament_execute_extensions)
  CMakeLists.txt:21 (ament_package)


CMake Error: File /tmp/tmpwwc9eqc9local_setup.zsh.in does not exist.
CMake Error at cmake/environment_hooks/ament_generate_package_environment.cmake:73 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  cmake/environment_hooks/ament_cmake_environment_hooks_package_hook.cmake:26 (ament_generate_package_environment)
  cmake/core/ament_execute_extensions.cmake:48 (include)
  cmake/core/ament_package.cmake:66 (ament_execute_extensions)
  CMakeLists.txt:21 (ament_package)

-- Configuring incomplete, errors occurred!
```

This seems to be cause by ament_package being installed as a .egg instead of into a subdirectory of the `site-packages` folder. What seems to be happening is ament_package uses `importlib.resources.path` functions to find the `local_setup.sh` scripts and as it's installed as a .egg the file is extracted to a temp file (hence the random prefix) and it gets clean up by the time the CMakeLists.txt actually references the file.

**Comment by mbatc** [comment]
I have got a fix for this so I will open a pull request soon

**Comment by mbatc** [comment]
Closing this for reasons mentioned in https://github.com/RoboStack/vinca/pull/42#issuecomment-1676834519

**Comment by traversaro** [comment]
Really cool, you are working on `emscripten32` support! If this is a problem of a given (future) version of setuptools, I would keep the issue open documenting at which version the problem occurs, as eventually we would need to update, and we would encounter this problem.
