### ISSUE TITLE
Bug? Should this two lines checking setup.cfg be swapped?

### ISSUE THREAD

**Issue by 0wu** [RoboStack/vinca#46]
https://github.com/RoboStack/vinca/blob/7cf990fb1373effd6934fd10fc7f1bc006422d77/vinca/templates/build_ament_python.sh.in#L7-L9

I assume $result should indicate if there's a setup.cfg

**Comment by Tobias-Fischer** [comment]
Ouch .. definitely a bug. /cc @traversaro

**Comment by traversaro** [comment]
Indeed, this seems a regression of https://github.com/RoboStack/vinca/commit/8be7ab86d554fa0c0e845f900b56b467e3092970 . Indeed, I tried with:

~~~
mamba create -n testdemotalker -c conda-forge -c robostack-staging ros-humble-demo-nodes-py ros-humble-ros2run
mamba activate testdemotalker
traversaro@IITBMP014LW012:~$ ros2 run demo_nodes_py demo_talker
No executable found
~~~

So we have a regression w.r.t. https://github.com/RoboStack/ros-humble/issues/41 .
