### ISSUE TITLE
patching missing dependency

### ISSUE THREAD

**Issue by sonelu** [RoboStack/vinca#57]
I have the following situation: a package (`backaward-ros`) has a missing dependency declared in the `package.xml` file and the build fails with a `findpackage` missing error (in this case the missing package is `ament-cmake-libraries`). The problem is that patching the `package.xml` file doesn't seem to have an effect: the build environment spec in the recipe is constructed **before** the patches are applied, and will miss that dependency. Later, after the source is cloned and patched the dependency is in package.xml, but is too late because the environment will not have it.

The only way I could let the build continue is by manually changing the recipe and add in the host part the additional dependency.

Is there another way to solve this situation (other than patching the upstream package to include the needed dependency).

**Comment by Tobias-Fischer** [comment]
Yes, you can declare them here: https://github.com/RoboStack/ros-humble/blob/main/patch/dependencies.yaml

thanks a lot for your efforts! Tobi

**Comment by sonelu** [comment]
Nice, thank you.
